name: aula10
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - banco

  banco:
    image: mariadb
    environment:
      MARIADB_USER: myuser
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: mydatabase
      MARIADB_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
